[package]
name = "sabitori-window"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sabitori-core.workspace = true
sabitori-gpu.workspace = true
sabitori-scene.workspace = true
sabitori-input.workspace = true
wgpu.workspace = true
winit.workspace = true
tracing.workspace = true
thiserror.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster.workspace = true
tracing-subscriber = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = [
    "Document",
    "Window",
    "Element",
    "HtmlCanvasElement",
    "Performance",
] }
console_error_panic_hook.workspace = true
console_log.workspace = true
log.workspace = true
